#!/usr/bin/env python3
x+y

# **** IMPORTANT***
#   x is the operand
#   + is the operator
#   YOU SHOUDL BE VERRY VERY GOOD WITH YOUR OPERATORS


#TYPES OF OPERATORS
1) ARITHMATIC OPERATORS
2) ASSIGNMENT OPERATORS
#INPUT AS VALUE OUTPUT AS VALUE

#INPUT AS A VALUE PROVIDE OUTPUT AS TRUE OR FALSE
3) COMPARISION OPERATORS
4) IDENTITY OPERATORS
5) MEMBERSHIP OPERATORS

#INPUT AS TRUE OR FALSE AND OUTPUT AS VALUE
6) LOGICAL OPERATORS

#INPUT AND OUT BOTH ARE VALUE BUT LOGICAL OPERATIONS WILL BE PERFORMED ON BITS AND BYTES AND LOGICAL OPERATIONS
# WILL BE PERFORMED ON THAT BITS AND BYTES
7) BITWISE OPERATORS
